server:
  port: ${CONFIG_PORT:8801}

spring:
  profiles:
    active: native # When use with spring.cloud.config.server.native
      
  application:
    name: config
  cloud:    config:
      override-system-properties: false      server:        native:          search-locations: D:/Training/dnj/config-data

eureka:
  client:
    enabled: true
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/
  instance:
    preferIpAddress: true
    appname: ${spring.application.name}