server:
  port: ${CONFIG_PORT:0}

spring:
  profiles:
    active: native # When use with spring.cloud.config.server.native
      
  application:
    name: config
  cloud:    config:      server:        native:          search-locations: D:/Training/dnj/config-data
  

eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/