server:
  port: ${GATEAY_PORT:8888}

spring:
  application:
    name: gateway

logging:
  file: 
    name: D:/logs/gateway.log
management:
  endpoint:
    health:
      show-details: always
      show-components: always
    logfile:
      external-file: D:/logs/gateway.log
    loggers:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  trace:
    http:
      enabled: true

eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/

zuul:
  host:
    connect-timeout-millis: 50000
    socket-timeout-millis: 50000
  routes:
    dnj-admin:
      path: /dnj-admin/**
      serviceId: dnj-admin
      stripPrefix: true
    config:
      path: /config/**
      serviceId: config
      stripPrefix: true
    user-service:
      path: /user-service/**
      serviceId: user-service
    admin-server:
      path: /admin-server/**
      serviceId: dnj-admin
      stripPrefix: true
    book-catalogue:
      path: /book-catalogue/**
      serviceId: book-catalogue
      stripPrefix: true
    book-inventory:
      path: /book-inventory/**
      serviceId: book-inventory
      stripPrefix: true
    book-recommendation:
      path: /book-recommendation/**
      serviceId: book-recommendation
      stripPrefix: true


