server:
  port: ${EUREKA_PORT:8761}


spring:
  application:
    name: discover  cloud:    config:      name: discover
      uri: http://localhost:8801  
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false