server:
  port: ${EUREKA_PORT:8761}
  
logging:
  file: 
    name: D:/logs/eureka.log
#  level:
#    root: DEBUG

spring:
  application:
    name: eureka
  profiles:
    active: local#  cloud:#    config:
#      uri: http://localhost:8801  
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false