server:
  port: ${PORT:0}

spring:
  application:
    name: dnj-admin
#  boot:
#    admin:
#      discovery:
#        ignored-services: gateway

eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/